name: Send Mail
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "email"
  email:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: ✨ Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.gmail.com
          port: 465
          account: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: devellany
          from: ${{secrets.MAIL_USERNAME}}
          to: ${{secrets.MAIL_USERNAME}}
          subject: Ready to upload to Spotify...
          body: |
            # Add audio file to the Wordpress RSS feed
            1. Once the audio files are in the repo, they can be added to the website as a post.
            Login in to the wordpress admin site and go into the settings. Click Posts on the left hand side and 'Add a new post'
            2. Add the Episode title in the format 'Episode XX- Title of Episode'. Then below the title type /audio and select the audio dropdown option.
            3. On the right pane, click on Post for the settings. Select the author. Select Podcast as the category (or it will NOT publish to Spotify). Write a brief excerpt describing the podcast episode.
            4. Finally, click on insert from url and enter the url of the audio file, located on Github. In the repo, locate the audio file, right click the View Raw link and copy the link address- this will be what you need.
            5. Publish and save all the changes and Spotify should pick up the new episode :)
          contentType: text/html
          attachments: '[{"path":"README.md"}]'